### ISSUE TITLE
[Request] Prices and for knifes

### ISSUE THREAD

**Issue by darknegative** [andrewda/CSGOItemDB.com#3]
I would like to add a fuction so knifes will be able to get a price on them too (Also if knifes like Karambit fade etc..) Items that are not on market should be priced as 450$ (is that possible?)

https://csgoitemdb.herokuapp.com/api/?key=exampleP&item=%E2%98%85%20Karambit%20|%20Ultraviolet

**Comment by andrewda** [comment]
First of all, you need to include the wear of the item (https://csgoitemdb.herokuapp.com/api/?key=exampleP&item=%E2%98%85%20Karambit%20%7C%20Ultraviolet%20%28Field-Tested%29 works fine). Second of all, I'm working on a way to get prices of items larger than the Steam Market can accommodate. Any help would be appreciated!

**Comment by andrewda** [comment]
#4

**Comment by darknegative** [comment]
Thank you. Issue closed.

**Comment by darknegative** [comment]
[Edit]

I see that the script doesnt get items that are worth more than 400$.

Is it possible atlatest to get the median price? 

What i mean is if you go here. 

https://csgoitemdb.herokuapp.com/api/?key=exampleP&item=%E2%98%85%20StatTrak%E2%84%A2%20M9%20Bayonet%20|%20Doppler%20%28Factory%20New%29 

The script says error instead of Steam Api that shows the median price 

http://steamcommunity.com/market/priceoverview/?currency=3&appid=730&market_hash_name=%E2%98%85%20StatTrak%E2%84%A2%20M9%20Bayonet%20|%20Doppler%20%28Factory%20New%29
