### ISSUE TITLE
Add a method to get items not on the market

### ISSUE THREAD

**Issue by andrewda** [andrewda/CSGOItemDB.com#4]
Need a way to get the prices of items worth more than $400

**Comment by darknegative** [comment]
Any update on that part?

**Comment by andrewda** [comment]
Working on it, @darknegative. Still trying to find a way. I may end up using the bitskins (or whatever it's called) API.

**Comment by mvegter** [comment]
You could use backpack.tf and/or csgofast api and take an average with the market price to prevent price manipulation.
