### ISSUE TITLE
[Request] Add the .sql file

### ISSUE THREAD

**Issue by darknegative** [andrewda/CSGOItemDB.com#7]
If its possible to add the sql file

**Comment by andrewda** [comment]
Sure I can add them in a min.

**Comment by darknegative** [comment]
Thank you!

**Comment by darknegative** [comment]
Did you add the .sql file on the project ? Becase for some reasson i cant see it.

**Comment by andrewda** [comment]
@darknegative sorry, I was busy. I'll try to upload it ASAP.

**Comment by andrewda** [comment]
https://github.com/andrewda/CSGOItemDB.com/blob/master/config.sql
